---
abstract: 'Upload documents to Google Docs'
author:
  - 'Daisuke Murase <typester@cpan.org>'
build_requires:
  Test::More: 0
distribution_type: module
generated_by: 'Module::Install version 0.72'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: WWW-Google-Docs-Upload
no_index:
  directory:
    - inc
    - t
requires:
  Moose: 0
  WWW::Mechanize: 0
version: 0.02
